import os
import time
from typing import Dict

import face_recognition
import pymongo

from modules.base import Base
from modules.text.gps.storage import DEFAULT_MONGO_URL, DEFAULT_MONGO_DB

parent_folder_path = os.path.abspath(os.path.dirname(__file__))
face_storage_path = os.path.join(parent_folder_path, "face_db")

mongo_client = pymongo.MongoClient(DEFAULT_MONGO_URL)
db = mongo_client[DEFAULT_MONGO_DB]
collection = db["profile"]
cursor = collection.find({})

known_face_encodings = []
profiles = []
for profile in cursor:
    # "id" (.jpg) is also face image name, generated by uuid.uuid4()
    # profilesDict[profile["id"]] = profile
    profiles.append(profile)

    face_path = os.path.join(face_storage_path, profile["id"] + ".jpg")
    face_array = face_recognition.load_image_file(face_path)
    known_face_encodings.append(face_recognition.face_encodings(face_array)[0])

tag = "Face recognition:"
print(tag, "loaded all", len(known_face_encodings), "known faces")


class Main(Base):
    def __init__(self, configs):
        self.configs = configs

    # input:
    # {
    #     frame: ndarray,
    #     face_locations: list
    # }
    def run(self, input: Dict):
        start_time = time.time()

        frame = input["frame"]
        face_locations = input["face_locations"]

        face_encodings = face_recognition.face_encodings(frame, face_locations)

        unrecognized_people_count = 0
        recognized_profile_indices = set()
        for face_encoding in face_encodings:
            results = face_recognition.compare_faces(known_face_encodings, face_encoding)
            match_indices = [i for i, x in enumerate(results) if x]
            for i in match_indices:
                recognized_profile_indices.add(i)
            if len(match_indices) == 0:
                unrecognized_people_count += 1

        recognized_profiles = [profiles[i] for i in recognized_profile_indices]
        end_time = time.time()

        print(tag, "in", "{:.2f}".format((end_time - start_time) * 1000), "(ms) recognized", len(recognized_profiles),
              "people:",
              [profile["name"] for profile in recognized_profiles])
        if unrecognized_people_count > 0:
            print(tag, "(WARNING)", unrecognized_people_count, "people not recognized")
